---
- name: Restart monitoring stack
  community.docker.docker_compose_v2:
    project_src: "{{ acr_monitoring_base_dir }}"
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    daemon_reload: true
    state: restarted
